//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use super::sea_orm_active_enums::CharacterFeatureEvent;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "character_feature")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub feature_id: Uuid,
    pub time_stamp: DateTime,
    pub event: Option<CharacterFeatureEvent>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature::Entity",
        from = "Column::FeatureId",
        to = "super::feature::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Feature,
    #[sea_orm(
        belongs_to = "super::player_character::Entity",
        from = "Column::CharacterId",
        to = "super::player_character::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PlayerCharacter,
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl Related<super::player_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerCharacter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
