//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "effect")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub feature_id: Uuid,
    pub path: String,
    pub value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature::Entity",
        from = "Column::FeatureId",
        to = "super::feature::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Feature,
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
