//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "player_character")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        super::character_feature::Relation::Feature.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::character_feature::Relation::PlayerCharacter
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
